name: crudjt-erlang benchmarks

on:
  workflow_dispatch:

jobs:
  build-and-test:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: x86_64
          - os: macos-latest
            arch: aarch64

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run benchmarks
        if: runner.os == 'Linux'
        run: |
          curl -fsSO https://elixir-lang.org/install.sh
          sh install.sh elixir@1.18.3 otp@27.2.3
          installs_dir=$HOME/.elixir-install/installs
          export PATH=$installs_dir/otp/27.2.3/bin:$PATH
          export PATH=$installs_dir/elixir/1.18.3-otp-27/bin:$PATH

          mkdir yo
          cd yo
          wget https://s3.amazonaws.com/rebar3/rebar3 && chmod +x rebar3
          ./rebar3 local install
          export PATH=/home/runner/.cache/rebar3/bin:$PATH
          rebar3 --version
          cd ../crud_jt_tests/crud_jt_performance_erlang

          rebar3 deps
          rebar3 escriptize
          _build/default/bin/my_lib

      - name: Run benchmarks
        if: runner.os == 'macOS'
        run: |
          brew install erlang rebar3 elixir
          cd crud_jt_tests/crud_jt_performance_erlang
          rebar3 deps
          rebar3 escriptize
          _build/default/bin/my_lib
